version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always
    entrypoint: ["sh", "-c", "ollama serve & sleep 2 && ollama pull llama3 && wait"]

  chatbot:
    build: .
    container_name: chatbot
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
